controller_manager:
  ros__parameters:
    update_rate: 50
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      publish_rate: 50
    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      joints:
        - joint0
        - joint1
      state_publish_rate: 50
      command_interfaces:
        - position
      state_interfaces:
        - position
        - velocity
        - effort
      gains:
        joint0: {p: 100.0, d: 10.0, i: 1.0}
        joint1: {p: 100.0, d: 10.0, i: 1.0}